#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     tiltingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     conveyorMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//different variables assigned as floats
float pie = 3.14159;
float track = 17;
float halfTrack = track / 2;
float wheelDiam = 3.88;
float wheelRadius = wheelDiam / 2;
float wheelCircumference = wheelDiam * PI;
float ticksPerInches =  2160 / (wheelCircumference);
float halfRobotCircumference = track*pie;
float robotCircumference = track*2*pie;
float feet = 168;
float motorSpeed = 50;

void moveBackward(float feet, float motorSpeed)
{
	nMotorEncoder[motorA] = 0;
	float inches= feet / 12;
	int nTicks=inches*ticksPerInches;
	while(abs(nMotorEncoder[motorA]) < nTicks)
	{
			motor[frontRightMotor] = motorSpeed;
			motor[frontLeftMotor] = -motorSpeed;
			motor[backRightMotor] = -motorSpeed;
			motor[backLeftMotor] = -motorSpeed;
	}
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
}
void moveFoward(float feet, float motorSpeed)
{
	nMotorEncoder[motorA] = 0;
	float inches= feet / 12;
	float nTicks=inches*ticksPerInches;

	while(abs(nMotorEncoder[motorA]) < nTicks)
	{
			motor[frontRightMotor] = motorSpeed;
			motor[frontLeftMotor] = motorSpeed;
			motor[backRightMotor] = motorSpeed;
			motor[backLeftMotor] = motorSpeed;
	}
	motor[frontLeftMotor] = 0;
	motor[frontRightMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
}
