#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int irSeekerV2(){
		int sensorVal= SensorValue[irSensor];

		//IR Sensor turned 22 degrees to the right
		if(sensorVal >= 5){
			//writeDebugStreamLine("3rd position");
		  return 3;
		}else if(sensorVal>=4){
			//writeDebugStreamLine("2nd position");
			return 2;
		}else{
			//writeDebugStreamLine("1st position");
			return 1;
		}
}

int irSeekerV2AfterRamp(){
		int sensorVal= SensorValue[irSensor];
		//IR Sensor turned 22 degrees to the right
		if(sensorVal <= 3){
			//writeDebugStreamLine("3rd position");
		  return 3;
		}
		else if(sensorVal == 0){
				//writeDebugStreamLine("2nd position");
			  return 1;
		}
		//else{
		//writeDebugStreamLine("1st position");
			//return 1;
		//}
}

//task main(){

	//while(true){
		//irSeekerV2AfterRamp();
		//int sensorVal= SensorValue[irSensor];
	//	writeDebugStreamLine("%d", sensorVal);

//}
