#pragma config(Sensor, S1,     irSensor,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


int irSeekerV2(){
		int sensorVal= SensorValue[irSensor];
		//IR Sensor turned 22 degrees to the right
		if(sensorVal<=6 && sensorVal!=0){
			//writeDebugStreamLine("1st position");
		  return 1;
		}else if(sensorVal>6){
			return 2;
		}else{
			return 3;
		}
}

int irSeekerV1(){
	int sensorVal= SensorValue[irSensor];
		//IR Sensor turned 10 degrees to the right
		//Robot moved forward 31 inches from edge of the wall
		if(sensorVal<=5 && sensorVal!=0){
		  return 1;
		}else if(sensorVal>5){
			//writeDebugStreamLine("2nd position");
		  return 2;
		}else{
			writeDebugStreamLine("3rd position");
			return 3;
		}
}
