#pragma config(Sensor, S1,     irSensor,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void irSeekerV2(){
		int sensorVal= SensorValue[irSensor];
		//IR Sensor turned 22 degrees to the right
		if(sensorVal<=6 && sensorVal!=0){
			writeDebugStreamLine("1st position");
		}else if(sensorVal>6){
			writeDebugStreamLine("2nd position");
		}else{
			writeDebugStreamLine("3rd position");
		}
}

void irSeekerV1(){
	int sensorVal= SensorValue[irSensor];
		//IR Sensor turned 10 degrees to the right
		//Robot moved forward 31 inches from edge of the wall
		if(sensorVal<=5 && sensorVal!=0){
			writeDebugStreamLine("1st position");
		}else if(sensorVal>5){
			writeDebugStreamLine("2nd position");
		}else{
			writeDebugStreamLine("3rd position");
		}
}
task main()
{
	while(true){

	}


}
