#pragma config(Sensor, dgtl1,  clickty_click,  sensorTouch)
#pragma config(Motor,  port2,           motorA,        tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//




task main(){
	int i=0;
	int x=0;

	while(x <= 4){
		motor[motorA]=50;
		while(SensorValue(clickty_click) == 1){
			i++;
		}
		if(i > 0){
			x++;
			i=0;
		}
	}
motor[motorA]=0;
}
