#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C3_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backright,     tmotorTetrix, openLoop)

#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//int gain=5;
/*move forward funtion*/
int x =0;
int diameter=4;
float pi = 3.14;
float ticksPerInches = 1440/diameter * pi;
float instruction [25][2];


void forward (int speed)
	{
		motor(frontleft)=speed;
		motor(frontright)=speed;
		motor(backleft)=speed;
		motor(backright)=speed;
		wait1Msec(10);
	}
/*move backward function*/
void backward (int speed)
	{
		motor(frontleft)=-speed;
		motor(frontright)=-speed;
		motor(backleft)=-speed;
		motor(backright)=-speed;
		wait1Msec(10);
	}
/*turn right funtion*/
void turnRight (int speed)
	{
		motor(frontleft)=speed;
		motor(backleft)=speed;
		wait1Msec(10);
	}
/*turn left funtion*/
void turnLeft (int speed)
	{
		motor(frontright)=speed;
		motor(backright)=speed;
		wait1Msec(10);
	}
/*right wheels movement*/
void rightWheels (int speed)
	{
		motor[frontright]=-speed;
		motor[backright]=speed;
		//wait1Msec(10);
	}
/*left wheels movement*/
void leftWheels (int speed)
	{
		motor[frontleft]=speed;
		motor[backleft]=speed;
		//wait1Msec(10);
	}

/*TANK DRIVE*/
void tankDrive()
	{
		motor[frontLeft] = ((-100.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0));
		motor[backLeft] = ((-100.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0));
		//right two motors controlled by the left joystick in controller one
		motor[frontRight] = ((100.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0));
		motor[backRight] = ((-100.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0));
	}
/*skim funtion*/
float skim(float v)
	{
		float gain =-0.5;
  // gain determines how much to skim off the top
  if (v > 1.0)
    return -((v - 1.0) * gain);
  else if (v < -1.0)
    return -((v + 1.0) * gain);
  else
    return 0;
	}
/*ARCADE DRIVE*/
void setMotorSpeed(float leftSide, float rightSide){
	motor[frontleft]=leftSide;
	motor[backleft]=leftSide;
	motor[frontright]=rightSide;
	motor[backright]=rightSide;
	}
float getDegrees(int nTicks){
}
float getFeet(int nTicks){
}
void storeVals(int i){
	if (joy1Btn(0)){
		nticks = getnticks();
		instructions [i] [0] = 1;
		//nticks = 0;
		//return i;
	}else if (joy1Btn(7)){
		nticks = getnticks();
		instructions [i] [0] = 2;
		//nticks = 0;
		//return i;
	}else if (joy1Btn(1)){
		//nticks = getnticks();
		if(instructions[i][0]==1){
			instructions [i] [1] = getFeet();
		}else if(instructions[i][0]==2){
			instructions [i] [1] = getDegrees();
			x++;
		}
		//nticks = 0;
	}


}
void arcadeDrive(float throttle, float turn)
	{
		float leftSpeed, rightSpeed;
		if (throttle >= 0.05){
			leftSpeed= throttle + turn;
			rightSpeed= throttle - turn;
			leftSpeed+= skim(leftSpeed);
			rightSpeed+= skim(rightSpeed);
		}
		else if(throttle < -0.05){
			leftSpeed= throttle - turn;
			rightSpeed= throttle + turn;
			leftSpeed+= skim(leftSpeed);
			rightSpeed+= skim(rightSpeed);
		}

		motor[frontLeft] = ((-100.0)*(leftSpeed/127.0)*(leftSpeed/127.0)*(leftSpeed/127.0));
		motor[backLeft] = ((-100.0)*(leftSpeed/127.0)*(leftSpeed/127.0)*(leftSpeed/127.0));
		//right two motors controlled by the left joystick in controller one
		motor[frontRight] = ((100.0)*(rightSpeed/127.0)*(rightSpeed/127.0)*(rightSpeed/127.0));
		motor[backRight] = ((-100.0)*(rightSpeed/127.0)*(rightSpeed/127.0)*(rightSpeed/127.0));

		//while(true){

		storeVals(x);

	}
/*void arcadeDrive1(float throttle, float turn)
	{
		float rightSpeed,leftSpeed,total;
		total = throttle + turn;
		excess = total - 1
		if excess < 0{
			excess = 0;
		}
		float reduce (power){
			if power > 1{
				return 1;
			}
		}
		if (throttle >= 0.05 and turn > 0){
			leftSpeed= reduce(throttle + turn);
			rightSpeed= -excess;
		}
		else if(throttle < -0.05){
			leftSpeed= reduce(throttle - turn);
			rightSpeed= reduce(throttle + turn);
		}
		motor[frontleft] = ((-100.0)*leftSpeed)/127.0;
		motor[backleft] = ((-100.0)*leftSpeed)/127.0;
		motor[frontright] = ((100.0)*rightSpeed)/127.0;
		motor[backright] = ((-100.0)*rightSpeed)/127.0;
	}*/
task main()
{
	while (true){
	 	arcadeDrive(joystick.joy1_y1, joystick.joy1_x2);
		//tankDrive();
	}
}
