#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorM,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     backLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "moveFunctions.c"
#include "JoystickDriver.c"
//#inlcude "TankArcadeDrive.c"
//different variables assigned as floats
	void knockPoleFromParking (){
			//position right wheel on the left side of the center of parking
			if(SensorValue(irSensor) < 7){					//position 1- beacon straight in front
				writeDebugStreamLine("1");
				/*
				moveFoward(34.0/12.0, 75);
			  wait1Msec(1.0);
			 	rightTwoWheelTurn(90.0, 75);
			 	wait1Msec(0.5);
			 	moveFoward(18.0/12.0, 100);
			 	wait1Msec(0.5);
			 	leftTwoWheelTurn(45.0,75.0);
			 	*/
			 	}
			else{
				moveFoward(2,75);
				rightTwoWheelTurn(15,75);
					if(SensorValue(irSensor)==9){								//position 2- beacon pointed to corner away from ramp
						writeDebugStreamLine("2");
						/*
						moveFoward(24.0/12.0, 75);
						wait1Msec(1);
						rightTwoWheelTurn(27.5, 85);
						wait1Msec(1);
						moveFoward(34.0/12.0, 150);
						wait1Msec(0.5);
						rightTwoWheelTurn(45.0, 75.0);
						*/
					}
					else if(SensorValue(irSensor)==0 ){								//position 3- beacon pointed at base of opposing ramp
						writeDebugStreamLine("3");
						/*
						moveFoward(20.0/12.0, 75);
						wait1Msec(1);
			  		rightTwoWheelTurn(90.0, 85);
			  		wait1Msec(0.5);
						moveFoward(36.0/12.0, 50);
						wait1Msec(2.0);
						leftTwoWheelTurn(56.0, 75);
						wait1Msec(0.5);
						moveFoward(40.0/12.0, 50);
						wait1Msec(0.5);
						rightTwoWheelTurn(45.0, 50);
						*/
			}
		}
	}

void rampGoal2Park (){
	moveFoward(6.75,75);
	leftOneWheelTurn(170,100);
	moveFoward(7,75);
	moveBackward(1,75);
	leftTwoWheelTurn(180,75);
	moveFoward(5.5,75);
	}

task main{
	knockPoleFromParking();
	}
