#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorM,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     backLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "moveFunctions.c"
//#inlcude "TankArcadeDrive.c"
//different variables assigned as floats
	void knockPoleFromParking (){
			//position right wheel on the left side of the center of parking
			wait10Msec(5);
			if(SensorValue(irSensor) <= 4){					//position 1- beacon straight in front
				writeDebugStreamLine("1");
				moveFoward(0.5, 75);
			  wait1Msec(1.0);
			 	rightTwoWheelTurn(45.0, 75);
			 	wait1Msec(0.5);
			 	moveFoward(3.4, 75);
			 	wait1Msec(0.5);
			 	leftTwoWheelTurn(52.0,75.0);
			 	wait1Msec(0.5);
			 	moveFoward(2.0,75);
			 	}
			else if (SensorValue(irSensor) == 5){
				moveFoward(2,75);
					if(SensorValue(irSensor)==4){								//position 2- beacon pointed to corner away from ramp
						writeDebugStreamLine("2");
						rightTwoWheelTurn(42.0, 85);
						wait1Msec(1);
						moveFoward(34.0/12.0, 150);
					}
					else if(SensorValue(irSensor)==5 ){								//position 3- beacon pointed at base of opposing ramp
						writeDebugStreamLine("3");
						moveFoward(1.0, 75);
						wait1Msec(1);
			  		rightOneWheelTurn(90.0, 85);
			}
		}
	}

void rampGoal2Park (){
	moveFoward(6.75,75);
	leftOneWheelTurn(170,100);
	moveFoward(7,75);
	moveBackward(1,75);
	leftTwoWheelTurn(180,75);
	moveFoward(5.5,75);
	}

task main{
	knockPoleFromParking();
	//moveFoward(1.0,75);
}
